#!/usr/bin/env python3
"""Generate the 6 missing SAT skill-drill pages from questions.json.

Picks first easy / medium / hard per category. Same interactive pattern as
the hand-built drills: selectable options, instant feedback with rationale,
bookmark via localStorage. Safe to re-run (overwrites generated files only).
"""
import html as htmllib
import io
import json
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, 'SAT', 'webapp', 'data')
SKILLS = os.path.join(BASE, 'SAT', 'Skills')

TARGETS = {
    'Information & Ideas': ('information_ideas_skill.html', 'sat_information_ideas_10_items.html', 'blue'),
    'Expression of Ideas': ('expression_ideas_skill.html', 'sat_expression_ideas_10_items.html', 'blue'),
    'Standard English Conventions': ('standard_conventions_skill.html', 'sat_standard_conventions_10_items.html', 'blue'),
    'Advanced Math': ('advanced_math_skill.html', 'sat_advanced_math_10_items.html', 'green'),
    'Problem Solving & Data Analysis': ('problem_solving_skill.html', 'sat_problem_solving_10_items.html', 'green'),
    'Geometry & Trigonometry': ('geometry_skill.html', 'sat_geometry_10_items.html', 'green'),
}
ACCENT = {'blue': '#3b82f6', 'green': '#10b981'}
LETTERS = ['A', 'B', 'C', 'D']


def pick_one(items, diff):
    for q in items:
        if q['difficulty'] == diff:
            return q
    return items[0]


def build(cat, fname, bank, color):
    items = [q for q in QUESTIONS if q['category'] == cat]
    chosen = [pick_one(items, d) for d in ('easy', 'medium', 'hard')]
    acc = ACCENT[color]
    slug = fname.replace('_skill.html', '')
    blocks, qd = [], {}
    for n, q in enumerate(chosen, 1):
        stim = ''
        if q.get('passage'):
            stim += '<p>%s</p>' % htmllib.escape(q['passage'])
        if q.get('stimulus') and q['stimulus'] not in (None, '---'):
            stim += '<p>%s</p>' % htmllib.escape(q['stimulus'])
        prompt = q.get('question') or q.get('stimulus') or 'Choose the best answer.'
        opts = ''.join(
            '<button class="opt" onclick="pick(this,%d,\'%s\')">%s) %s</button>' % (
                n, q['answer'], L, htmllib.escape(o)) for L, o in zip(LETTERS, q['options']))
        blocks.append(
            '<div class="q" id="q%d"><h3>Q%d \u2014 %s: %s</h3>%s'
            '<p><strong>%s</strong></p>%s<div id="fb%d"></div></div>'
            % (n, n, q['difficulty'].capitalize(), htmllib.escape(q['skill']),
               stim, htmllib.escape(prompt), opts, n))
        qd[str(n)] = {'key': q['answer'], 'rat': q['rationale'], 'qid': q['id']}
    return '''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<!-- generated by scripts/build_skill_drills.py -->
<title>SAT Skill \u2014 %s</title>
<style>@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;800&display=swap');
body{font-family:'Plus Jakarta Sans',system-ui,sans-serif;background:#f8fafc;color:#0f172a;
line-height:1.6;padding:2rem}.wrap{max-width:800px;margin:0 auto}
h1{font-size:1.8rem;border-left:6px solid %s;padding-left:1rem}
.q{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:1.5rem;margin:1.5rem 0;
box-shadow:0 4px 6px -1px rgb(0,0,0,.05)}
.opt{display:block;width:100%%;text-align:left;padding:.7rem;border:1px solid #d1d5db;border-radius:8px;
margin:.4rem 0;cursor:pointer;background:#fff;font:inherit}.opt:hover{background:#f1f5f9}
.opt.selected{border-color:%s;background:#eff6ff}
.feedback{margin-top:1rem;padding:1rem;border-radius:8px;font-weight:600}
.correct{background:#ecfdf5;border-left:4px solid #10b981}
.wrong{background:#fef2f2;border-left:4px solid #ef4444}
button.go{background:%s;color:#fff;border:none;padding:.7rem 1.4rem;border-radius:8px;
font-weight:700;cursor:pointer}.bookmark{cursor:pointer;color:#f59e0b;font-size:1.2rem}
a{color:%s}</style></head><body><div class="wrap">
<h1>SAT Skill Drill \u2014 %s <span onclick="toggleBookmark(1)" class="bookmark" title="Bookmark">\u2b50</span></h1>
<p>Pick an answer for instant feedback with rationale. Use the portal toolbar
(<strong>Pen / Highlight / Mark</strong>) to annotate.</p>
%s
<button class="go" onclick="clearAll()">Clear Selections</button>
<p style="margin-top:2rem"><a href="../index.html">\u2190 Master Portal</a> |
<a href="../Question_Banks/%s">35-Item Bank \u2192</a></p></div>
<script>
const QD = %s;
let picks={};
function pick(btn,q,correct){
document.querySelectorAll('#q'+q+' .opt').forEach(b=>b.classList.remove('selected'));
btn.classList.add('selected');picks[q]=btn.textContent.trim().charAt(0);
const d=QD[String(q)],fb=document.getElementById('fb'+q);
if(picks[q]===d.key){fb.className='feedback correct';fb.innerHTML='<b>Correct.</b> '+escapeHtml(d.rat);}
else{fb.className='feedback wrong';fb.innerHTML='<b>Incorrect.</b> Correct answer: <b>'+d.key+'</b><br>'+escapeHtml(d.rat);}}
function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function clearAll(){document.querySelectorAll('.opt').forEach(b=>b.classList.remove('selected'));
document.querySelectorAll('.feedback').forEach(b=>{b.className='';b.innerHTML='';});picks={};}
function toggleBookmark(id){const s=document.querySelector('h1 .bookmark');
if(s.innerText==='\u2b50'){s.innerText='\u2605';localStorage.setItem('sat_bookmark_%s_'+id,'1');}
else{s.innerText='\u2b50';localStorage.removeItem('sat_bookmark_%s_'+id);}}
</script></body></html>''' % (
        cat, acc, acc, acc, acc, cat, '\n'.join(blocks), bank,
        json.dumps(qd, ensure_ascii=False), slug, slug)


QUESTIONS = json.load(io.open(os.path.join(DATA, 'questions.json'), encoding='utf-8'))
if __name__ == '__main__':
    for cat, (fname, bank, color) in TARGETS.items():
        html = build(cat, fname, bank, color)
        with io.open(os.path.join(SKILLS, fname), 'w', encoding='utf-8') as f:
            f.write(html)
        print('built Skills/' + fname)
